### ISSUE TITLE
Issues Opening Videos in DARMA

### ISSUE THREAD

**Issue by jgc5244** [jmgirard/DARMA#6]
Do the video files have to be in a certain file format, or specific video/audio codecs, to work in DARMA? The videos open and play in VLC media player, but will not when opening through DARMA.

**Comment by jmgirard** [comment]
DARMA uses VLC to open and play video files, so it surprises me that a video would work in VLC but not in DARMA. Are you getting an error message, or what happens when you try to load the video in DARMA?

**Comment by jgc5244** [comment]
There is no error message. Nothing happens, it stays at the page where you select a media file. It only happens with some videos.

**Comment by jmgirard** [comment]
Ah, perhaps the meta-data for those files is corrupted. I suggest you transcode them, which should repair the meta-data. You can do this easily (and for free) by running the files through [HandBrake](http://handbrake.fr).

**Comment by jmross13** [comment]
Hi Jeff,

I am having a slightly different problem opening videos in DARMA on only one of my Windows 7-10 computers. I am able to open the videos in VLC media player, and I am able to open them without a problem when using the "Review Ratings" feature. However, when using the "Collect Ratings" feature, the videos are just a green screen with working audio. Any thoughts on this?

Thanks!

**Comment by jmgirard** [comment]
First off, I'd restart the computer and try again. If the problem persists, I would make sure all the affected computer's drivers were updated (this is a good idea in general). If the problem still persists, I would try some other videos (ideally from different projects/cameras/encodings) to see if the issue is specific to certain types of files. Try this stuff out and we can go from there if necessary.
